CLASS zcl_demo_d01e01_000 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES if_oo_adt_classrun.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_demo_d01e01_000 IMPLEMENTATION.

  METHOD if_oo_adt_classrun~main.
      
  ENDMETHOD.

ENDCLASS.